### ISSUE TITLE
facing issue Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by vvonchain** [ExponentialML/ComfyUI_ELLA#21]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/teamspace/studios/this_studio/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_ELLA/ella.py", line 68, in load_ella
    t5_model = T5TextEmbedder(t5_path).to(self.device, self.dtype)
  File "/teamspace/studios/this_studio/ComfyUI/custom_nodes/ComfyUI_ELLA/ella_model/model.py", line 240, in __init__
    self.model = T5EncoderModel.from_pretrained(pretrained_path)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3706, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/modeling_utils.py", line 4091, in _load_pretrained_model
    state_dict = load_state_dict(shard_file)
  File "/home/zeus/miniconda3/envs/cloudspace/lib/python3.10/site-packages/transformers/modeling_utils.py", line 503, in load_state_dict
    with safe_open(checkpoint_file, framework="pt") as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

**Comment by Limbicnation** [comment]
Encountered the same issue with the model is downloaded from: https://huggingface.co/QQGYLab/ELLA/blob/main/ella-sd1.5-tsc-t5xl.safetensors

**Comment by Limbicnation** [comment]
> Encountered the same issue with the model is downloaded from: https://huggingface.co/QQGYLab/ELLA/blob/main/ella-sd1.5-tsc-t5xl.safetensors

Resolved the error by addressing missing components: the FLAN-T5-XL models were not correctly placed in `ComfyUI/models/t5_model/flan-t5-xl/`, and the ELLA model was incorrectly located in `ComfyUI/models/ella`.

**Comment by Jhaul1974** [comment]
> > Encountered the same issue with the model is downloaded from: https://huggingface.co/QQGYLab/ELLA/blob/main/ella-sd1.5-tsc-t5xl.safetensors
> 
> Resolved the error by addressing missing components: the FLAN-T5-XL models were not correctly placed in `ComfyUI/models/t5_model/flan-t5-xl/`, and the ELLA model was incorrectly located in `ComfyUI/models/ella`.

same issue which is the correct location?
tanks

**Comment by quixot1c** [comment]
From the Readme of this repo:

In summary, you should have the following model directory structure:
    ComfyUI/models/ella/ella-sd1.5-tsc-t5xl.safetensors
    ComfyUI/models/t5_model/flan-t5-xl/all_downloaded_t5_models

**Comment by Mladen2802** [comment]
I am still getting same issue. My directory structure looks ok. 
![image](https://github.com/ExponentialML/ComfyUI_ELLA/assets/111195678/20048e7d-53e0-4912-8c2a-db2d256a6665)

**Comment by JakeSSRN** [comment]
Same issue. All models are placed correctly. Any luck?
